WITH 
q3a_cte (YEAR, MONTH, Sum_Doses)
AS
(
SELECT CAST(YEAR(TRANSACTION_DATE) AS VARCHAR(8)), MONTH(TRANSACTION_DATE), SUM(DOSAGE_UNIT) 
FROM CSE532.DEA_NY 
GROUP BY (YEAR(TRANSACTION_DATE), MONTH(TRANSACTION_DATE))
)
SELECT YEAR ||
CASE 
    WHEN (  CAST( MONTH AS INT)  < 10 ) 
         THEN '0'  || CAST( MONTH AS INT)
    ELSE CAST ( MONTH AS CHAR(2) )
END AS DATE_YYYYMM, SUM_DOSES,
SUM(SUM_DOSES) OVER (ORDER BY YEAR, MONTH ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS SMOOTH_SUM,
ROUND(AVG(SUM_DOSES) OVER (ORDER BY YEAR, MONTH ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING),2) AS SMOOTH_AVG
FROM q3a_cte 