WITH 
ZIPPOP_CTE AS
(
SELECT DISTINCT ZIP, ZPOP
FROM CSE532.ZIPPOP
WHERE ZPOP <> 0
),
DEA_NY_CTE AS
(
SELECT BUYER_ZIP, SUM(MME) AS MME
FROM CSE532.DEA_NY
GROUP BY BUYER_ZIP
),
NORMALISED_VALUES AS
(
SELECT CAST(ZIP AS VARCHAR(8)) AS ZIP, CAST(BUYER_ZIP AS VARCHAR(8)) AS BUYER_ZIP, ZPOP, ROUND(MME,2) AS MME, ROUND(MME/ZPOP,2) AS NORMALISED_MME,
DENSE_RANK () OVER (ORDER BY MME/ZPOP DESC) AS RANKING
FROM ZIPPOP_CTE, DEA_NY_CTE
WHERE ZIP = BUYER_ZIP
)
SELECT * FROM NORMALISED_VALUES
WHERE RANKING <=5